name: Build on each PR
env: 
  CI: true
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: corepack enable && yarn && yarn install
        working-directory: ./movie-service
      - name: Lint
        run: yarn run lint
        working-directory: ./movie-service
